# Generated by Django 3.1.2 on 2020-10-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regionroad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='region_id',
            new_name='region',
        ),
    ]
