# Generated by Django 3.1.2 on 2020-10-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20201013_0814'),
        ('account', '0002_auto_20201013_0814'),
        ('pitomnik', '0002_auto_20201013_0814'),
        ('regionroad', '0002_auto_20201013_0641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
