# Generated by Django 3.1.2 on 2020-11-07 06:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0003_delete_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="road",
            name="length",
        ),
        migrations.RemoveField(
            model_name="road",
            name="region",
        ),
        migrations.CreateModel(
            name="RoadDistrict",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                (
                    "road_slice",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=2
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regionroad.district",
                    ),
                ),
                (
                    "road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regionroad.road",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="road",
            name="district",
            field=models.ManyToManyField(
                related_name="roads",
                through="regionroad.RoadDistrict",
                to="regionroad.District",
            ),
        ),
    ]
