# Generated by Django 3.1.2 on 2020-11-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0004_auto_20201107_0631"),
    ]

    operations = [
        migrations.AddField(
            model_name="roaddistrict",
            name="requirement",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
