# Generated by Django 3.1.2 on 2020-11-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0005_roaddistrict_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="roaddistrict",
            name="road_from",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roaddistrict",
            name="road_to",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
