# Generated by Django 3.1.2 on 2020-11-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0007_remove_roaddistrict_road_slice"),
        ("regionroad", "0006_region_code"),
    ]

    operations = []
