# Generated by Django 3.1.2 on 2020-11-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0008_merge_20201111_1009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="code",
            field=models.CharField(max_length=10),
        ),
    ]
