# Generated by Django 3.1.2 on 2020-11-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0009_auto_20201111_1139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roads",
                to="regionroad.roadtype",
            ),
            preserve_default=False,
        ),
    ]
