# Generated by Django 3.1.2 on 2020-11-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0010_auto_20201111_1904"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Махаллий"),
                    ("GOVERNMENT", "Давлат"),
                    ("INTERNATION", "Халқаро"),
                ],
                max_length=12,
            ),
        ),
        migrations.DeleteModel(
            name="RoadType",
        ),
    ]
