# Generated by Django 3.1.2 on 2020-11-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0011_auto_20201112_0659"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Маҳаллий"),
                    ("GOVERNMENT", "Давлат"),
                    ("INTERNATION", "Халқаро"),
                ],
                max_length=12,
            ),
        ),
    ]
