# Generated by Django 3.1.2 on 2020-11-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0014_auto_20201124_1552"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.IntegerField(
                choices=[(1, "Халқаро"), (2, "Давлат"), (3, "Маҳаллий")]
            ),
        ),
    ]
