# Generated by Django 3.1.2 on 2020-10-21 10:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('regionroad', '0003_delete_organization'),
        ('pitomnik', '0002_auto_20201013_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitomnik',
            name='district',
        ),
        migrations.AddField(
            model_name='pitomnik',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pitomnik', to='regionroad.region'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PitomnikImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.ImageField(upload_to='pitomnik_images')),
                ('Pitomnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitomnik_image', to='pitomnik.pitomnik')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
