# Generated by Django 3.1.2 on 2020-10-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0003_auto_20201021_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitomnikimage',
            old_name='Pitomnik',
            new_name='pitomnik',
        ),
    ]
