# Generated by Django 3.1.2 on 2020-10-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0005_auto_20201025_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitomnikplants',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Pitomnik Plants'},
        ),
        migrations.RenameField(
            model_name='pitomnikplants',
            old_name='quantity',
            new_name='initial_quantity',
        ),
        migrations.AddField(
            model_name='pitomnikplants',
            name='left_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
