# Generated by Django 3.1.2 on 2020-10-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0006_auto_20201026_0547"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantedplants",
            name="pitomnik_plant",
        ),
        migrations.AddField(
            model_name="plantedplants",
            name="pitomnik",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pitomnik.pitomnik",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plantedplants",
            name="plant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pitomnik.plant",
            ),
            preserve_default=False,
        ),
    ]
