# Generated by Django 3.1.2 on 2020-10-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0006_auto_20201026_0547"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pitomnik",
            name="region",
        ),
    ]
