# Generated by Django 3.1.2 on 2020-10-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0007_auto_20201026_1625"),
        ("pitomnik", "0007_remove_pitomnik_region"),
    ]

    operations = []
