# Generated by Django 3.1.2 on 2020-10-28 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pitomnik", "0010_auto_20201028_0543"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pitomnikplants",
            name="added_by",
        ),
        migrations.RemoveField(
            model_name="pitomnikplants",
            name="area",
        ),
        migrations.RemoveField(
            model_name="pitomnikplants",
            name="expected_ready_time",
        ),
        migrations.RemoveField(
            model_name="pitomnikplants",
            name="initial_quantity",
        ),
        migrations.RemoveField(
            model_name="pitomnikplants",
            name="left_quantity",
        ),
        migrations.RemoveField(
            model_name="pitomnikplants",
            name="planted_type",
        ),
        migrations.AddField(
            model_name="pitomnikplants",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PitomnikPlantItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ("initial_quantity", models.PositiveIntegerField()),
                ("left_quantity", models.PositiveIntegerField()),
                (
                    "planted_type",
                    models.CharField(
                        choices=[("SPROUT", "Ниҳолдан"), ("SEED", "Уруғдан")],
                        max_length=10,
                    ),
                ),
                ("area", models.FloatField()),
                ("expected_ready_time", models.DateField()),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pitomnik_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pitomnik.pitomnikplants",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
