# Generated by Django 3.1.2 on 2020-10-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0011_auto_20201028_0859"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitomnikplantitems",
            name="pitomnik_plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="pitomnik.pitomnikplants",
            ),
        ),
    ]
