# Generated by Django 3.1.2 on 2020-10-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0012_auto_20201028_0901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitomnikplants",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
