# Generated by Django 3.1.2 on 2020-10-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0013_auto_20201028_0927"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pitomnikplants",
            unique_together={("pitomnik", "plant")},
        ),
    ]
