# Generated by Django 3.1.2 on 2020-10-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0014_auto_20201028_0941"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitomnik",
            name="kontr",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pitomnikimage",
            name="image",
            field=models.ImageField(upload_to="pitomnik_image/2020-10-29"),
        ),
        migrations.AlterField(
            model_name="plantedplantimage",
            name="image",
            field=models.ImageField(
                upload_to="planted_plant_image/2020-10-29"
            ),
        ),
    ]
