# Generated by Django 3.1.2 on 2020-10-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0003_delete_organization"),
        ("pitomnik", "0015_auto_20201029_0915"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantedplants",
            name="district",
            field=models.ForeignKey(
                default=405,
                on_delete=django.db.models.deletion.CASCADE,
                to="regionroad.district",
            ),
            preserve_default=False,
        ),
    ]
