# Generated by Django 3.1.2 on 2020-10-29 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pitomnik", "0017_irrigation_irrigation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="irrigation",
            name="added_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="irrigationtype",
            name="added_by",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landscapejob",
            name="added_by",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savingjob",
            name="added_by",
            field=models.ForeignKey(
                default=21,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.user",
            ),
            preserve_default=False,
        ),
    ]
