# Generated by Django 3.1.2 on 2020-10-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0018_auto_20201029_1540"),
        ("pitomnik", "0016_plantedplants_district"),
    ]

    operations = []
