# Generated by Django 3.1.2 on 2020-10-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_auto_20201013_0859"),
        ("pitomnik", "0019_merge_20201029_1556"),
    ]

    operations = [
        migrations.AddField(
            model_name="irrigation",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="irrigationtype",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landscapejob",
            name="organization",
            field=models.ForeignKey(
                default=21,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savingjob",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pitomnikimage",
            name="image",
            field=models.ImageField(upload_to="pitomnik_image/2020-10-30"),
        ),
        migrations.AlterField(
            model_name="plantedplantimage",
            name="image",
            field=models.ImageField(
                upload_to="planted_plant_image/2020-10-30"
            ),
        ),
    ]
