# Generated by Django 3.1.2 on 2020-10-31 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0020_auto_20201030_1102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irrigation",
            name="irrigation_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="irrigations",
                to="pitomnik.irrigationtype",
            ),
        ),
        migrations.AlterField(
            model_name="pitomnikimage",
            name="image",
            field=models.ImageField(upload_to="pitomnik_images/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="plantedplantimage",
            name="image",
            field=models.ImageField(
                upload_to="planted_plant_images/%Y/%m/%d/"
            ),
        ),
    ]
