# Generated by Django 3.1.2 on 2020-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0021_auto_20201031_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irrigation",
            name="irrigation_type",
            field=models.CharField(
                choices=[
                    ("STREAMS", "Ариқлар орқали"),
                    ("BY_CAR", "Автотранспортда"),
                    ("PUMP_AND_MOTOR", "Насос ва мотопомпалар"),
                    ("DRIP_AND_RAIN", "Томчилатиб, ёмғирлатиб"),
                ],
                max_length=60,
            ),
        ),
        migrations.DeleteModel(
            name="IrrigationType",
        ),
    ]
