# Generated by Django 3.1.2 on 2020-11-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0022_auto_20201102_1035"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="irrigation",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="landscapejob",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="pitomnik",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="pitomnikimage",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="pitomnikplantitems",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="plant",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="plantedplantimage",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="planttype",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="savingjob",
            options={"ordering": ("-created_at",)},
        ),
    ]
