# Generated by Django 3.1.2 on 2020-11-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0023_auto_20201102_1433"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="irrigation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="landscapejob",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pitomnik",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pitomnikimage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pitomnikplantitems",
            options={},
        ),
        migrations.AlterModelOptions(
            name="plant",
            options={},
        ),
        migrations.AlterModelOptions(
            name="plantedplantimage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="planttype",
            options={},
        ),
        migrations.AlterModelOptions(
            name="savingjob",
            options={},
        ),
    ]
