# Generated by Django 3.1.2 on 2020-11-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0024_auto_20201102_1435"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantedplants",
            name="district",
        ),
        migrations.RemoveField(
            model_name="plantedplants",
            name="location",
        ),
        migrations.RemoveField(
            model_name="plantedplants",
            name="pitomnik_plant",
        ),
        migrations.AddField(
            model_name="plantedplants",
            name="pitomnik",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pitomnik.pitomnik",
            ),
        ),
        migrations.AddField(
            model_name="plantedplants",
            name="plant",
            field=models.ForeignKey(
                default=42,
                on_delete=django.db.models.deletion.CASCADE,
                to="pitomnik.plant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plantedplants",
            name="plant_source",
            field=models.CharField(
                choices=[
                    ("PITOMNIK", "Питомникдан"),
                    ("FOREST", "Ўрмондан"),
                    ("OTHERS", "Бошқа"),
                ],
                default="OTHERS",
                max_length=15,
            ),
        ),
    ]
