# Generated by Django 3.1.2 on 2020-11-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0005_roaddistrict_requirement"),
        ("pitomnik", "0025_auto_20201107_0730"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantedplants",
            name="road_district",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="regionroad.roaddistrict",
            ),
            preserve_default=False,
        ),
    ]
