# Generated by Django 3.1.2 on 2020-11-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0026_plantedplants_road_district"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantedplants",
            name="road",
        ),
    ]
