# Generated by Django 3.1.3 on 2020-11-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0027_remove_plantedplants_road'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitomnik',
            options={'ordering': ('-id',)},
        ),
    ]
