# Generated by Django 3.1.3 on 2020-11-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0028_auto_20201109_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitomnikplantitems',
            options={'ordering': ('-id',)},
        ),
    ]
