# Generated by Django 3.1.2 on 2020-11-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0029_auto_20201110_1206"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantedplants",
            name="road_slice",
        ),
    ]
