# Generated by Django 3.1.2 on 2020-11-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0030_remove_plantedplants_road_slice"),
        ("pitomnik", "0029_auto_20201109_1332"),
    ]

    operations = []
