# Generated by Django 3.1.2 on 2020-11-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0031_merge_20201111_1009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantedplants",
            name="plant_source",
            field=models.CharField(
                choices=[
                    ("PITOMNIK", "Питомникдан"),
                    ("FOREST", "Ўрмондан"),
                    ("OTHERS", "Бошқа"),
                ],
                default="OTHERS",
                max_length=15,
                verbose_name="Манба",
            ),
        ),
    ]
