# Generated by Django 3.1.2 on 2020-11-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0032_auto_20201111_1904"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="plant_type",
        ),
        migrations.DeleteModel(
            name="PlantType",
        ),
    ]
