# Generated by Django 3.1.2 on 2020-11-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0033_auto_20201112_0703"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="plant_type",
            field=models.CharField(
                choices=[
                    ("LEAF_SHAPED", "Япрок баргли"),
                    ("CONIFEROUS", "Игна Баргли"),
                    ("BUSH", "Бута"),
                ],
                default="BUSH",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
