# Generated by Django 3.1.2 on 2020-11-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0034_plant_plant_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plant",
            old_name="plant_type",
            new_name="type",
        ),
    ]
