# Generated by Django 3.1.3 on 2020-11-14 07:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pitomnik', '0035_auto_20201112_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitomnikplants',
            name='action_type',
            field=models.CharField(choices=[('Import', 'Import'), ('Export', 'Export')], default='Import', max_length=10),
        ),
        migrations.AddField(
            model_name='pitomnikplants',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitomnikplants',
            name='plant_field',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pitomnikplants',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('SPROUT', 'Ниҳолдан'), ('SEED', 'Уруғдан')], max_length=10),
        ),
        migrations.AddField(
            model_name='pitomnikplants',
            name='readiness_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pitomnikplants',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
