# Generated by Django 3.1.2 on 2020-11-13 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0013_auto_20201112_1046"),
        ("pitomnik", "0035_auto_20201112_0715"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savingjob",
            name="road",
        ),
        migrations.RemoveField(
            model_name="savingjob",
            name="road_slice",
        ),
        migrations.AddField(
            model_name="savingjob",
            name="road_district",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="regionroad.roaddistrict",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savingjob",
            name="road_from",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savingjob",
            name="road_to",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
