# Generated by Django 3.1.3 on 2020-11-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0036_auto_20201114_0717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PitomnikPlantItems',
        ),
    ]
