# Generated by Django 3.1.2 on 2020-11-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0036_auto_20201113_0533"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savingjob",
            name="tree_len",
        ),
        migrations.RemoveField(
            model_name="savingjob",
            name="tree_quantity",
        ),
    ]
