# Generated by Django 3.1.2 on 2020-11-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0037_delete_pitomnikplantitems'),
        ('pitomnik', '0036_newirrigation'),
    ]

    operations = [
    ]
