# Generated by Django 3.1.2 on 2020-11-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0038_auto_20201114_1001"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pitomnikplants",
            unique_together=set(),
        ),
    ]
