# Generated by Django 3.1.2 on 2020-11-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0037_auto_20201114_0955'),
        ('pitomnik', '0038_merge_20201114_1621'),
        ('pitomnik', '0039_auto_20201114_1036'),
    ]

    operations = [
    ]
