# Generated by Django 3.1.2 on 2020-11-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0041_auto_20201114_1732"),
        ("pitomnik", "0040_merge_20201114_1359"),
    ]

    operations = []
