# Generated by Django 3.1.2 on 2020-11-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0042_merge_20201119_0742"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newirrigation",
            old_name="road_district",
            new_name="road",
        ),
        migrations.AlterField(
            model_name="pitomnikimage",
            name="pitomnik",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="pitomnik.pitomnik",
            ),
        ),
    ]
