# Generated by Django 3.1.2 on 2020-11-21 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20201013_0859'),
        ('pitomnik', '0043_auto_20201121_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newirrigation',
            old_name='road',
            new_name='road_district',
        ),
        migrations.AddField(
            model_name='newirrigation',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newirrigation',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newirrigation',
            name='artesian_well',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newirrigation',
            name='drop',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newirrigation',
            name='rain',
            field=models.FloatField(default=0),
        ),
    ]
