# Generated by Django 3.1.2 on 2020-11-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regionroad', '0013_auto_20201112_1046'),
        ('pitomnik', '0044_auto_20201121_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landscapejob',
            name='road',
        ),
        migrations.AddField(
            model_name='landscapejob',
            name='road_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='regionroad.roaddistrict'),
            preserve_default=False,
        ),
    ]
