# Generated by Django 3.1.2 on 2020-11-24 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0046_auto_20201124_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitomnikplants',
            name='planted_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
