# Generated by Django 3.1.2 on 2020-11-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0047_pitomnikplants_planted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantedplants",
            name="planting_side",
            field=models.CharField(
                choices=[
                    ("RIGHT", "Ўнг тараф"),
                    ("LEFT", "Чап тараф"),
                    ("BOTH", "Ўнг ва Чап тараф"),
                ],
                default="BOTH",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
