# Generated by Django 3.1.2 on 2020-11-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0048_agrotechnics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agrotechnics',
            new_name='PitomnikSavingJob',
        ),
    ]
