# Generated by Django 3.1.2 on 2020-11-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0049_auto_20201125_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitomniksavingjob',
            name='plant',
        ),
        migrations.AddField(
            model_name='pitomniksavingjob',
            name='pitomnik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pitomnik.pitomnik'),
            preserve_default=False,
        ),
    ]
