# Generated by Django 3.1.2 on 2020-11-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0050_auto_20201125_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitomniksavingjob',
            name='plants',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pitomnik.plant'),
            preserve_default=False,
        ),
    ]
