# Generated by Django 3.1.2 on 2020-11-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0049_plantedplants_planted_date'),
        ('pitomnik', '0051_pitomniksavingjob_plants'),
    ]

    operations = [
    ]
