# Generated by Django 3.1.2 on 2020-11-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0052_merge_20201126_1640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitomnikplants",
            name="readiness_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
