# Generated by Django 3.1.2 on 2020-12-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0054_pitomniksavingjobimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigation',
            name='irrigation_type',
            field=models.CharField(choices=[('STREAMS', 'Ариқлар ва қувурлар орқали'), ('BY_CAR', 'Автотранспортда'), ('PUMP_AND_MOTOR', 'Насос ва мотопомпалар'), ('DRIP_AND_RAIN', 'Томчилатиб, ёмғирлатиб')], max_length=60),
        ),
        migrations.AlterField(
            model_name='newirrigation',
            name='drop',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pitomnikplants',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
