# Generated by Django 3.1.2 on 2020-12-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0056_pitomnikplants_dried'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitomnikplants',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
