# Generated by Django 3.1.2 on 2020-12-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0057_auto_20201215_1606"),
        ("pitomnik", "0057_landscapejobimage"),
    ]

    operations = []
