# Generated by Django 3.1.2 on 2020-12-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0059_irrigationimage_newirrigationimage_savingjobimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savingjobimage",
            old_name="landscapejob",
            new_name="savingjob",
        ),
    ]
