# Generated by Django 3.1.2 on 2020-12-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0060_auto_20201218_1203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitomnik",
            name="kontr",
            field=models.CharField(max_length=255),
        ),
    ]
