# Generated by Django 3.1.2 on 2020-12-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0062_saving"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Saving",
        ),
    ]
