# Generated by Django 3.1.2 on 2020-12-23 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pitomnik", "0063_delete_saving"),
    ]

    operations = [
        migrations.CreateModel(
            name="PitomnikPlantImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="pitomnikplant_images/%Y/%m/%d/"
                    ),
                ),
                (
                    "pitomnik_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pitomnik.pitomnikplants",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
