# Generated by Django 3.1.2 on 2021-03-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0001_initial'),
        # ('pitomnik', '0066_auto_20210317_1324'),
    ]

    operations = [
    ]
