# Generated by Django 3.1.2 on 2021-05-12 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regionroad', '0001_initial'),
        ('pitomnik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantedplants',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regionroad.district'),
        ),
        migrations.AlterField(
            model_name='pitomnikplants',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantedplants',
            name='metr',
            field=models.IntegerField(null=True),
        ),
    ]
