# Generated by Django 3.1.2 on 2021-03-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0001_initial'),
        ('pitomnik', '0001_initial'),
    ]

    operations = [
    ]
