# Generated by Django 3.1.2 on 2021-05-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0068_auto_20210512_0729'),
        ('pitomnik', '0064_pitomnikplantimage'),
        ('pitomnik', '0067_plantedplants_district'),
        ('pitomnik', '0067_merge_20210324_1045'),
        ('pitomnik', '0066_auto_20210425_1042'),
        ('pitomnik', '0068_merge_20210325_1407'),
        ('pitomnik', '0069_merge_20210412_1045'),
        ('pitomnik', '0065_plantedplants_metr'),
    ]

    operations = [
    ]
