# Generated by Django 3.1.2 on 2021-05-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitomnik', '0072_auto_20210512_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantedplants',
            old_name='district_id',
            new_name='district',
        ),
    ]
