# Generated by Django 3.1.2 on 2020-12-05 07:08

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20201013_0859'),
        ('regionroad', '0015_auto_20201124_1552'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyProductionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('money_amount_plan', models.DecimalField(decimal_places=2, max_digits=13)),
                ('road_address', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), max_length=2, size=None)),
                ('year', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regionroad.road')),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('organization', 'road', 'road_address', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyProductionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('monthly_plan_money', models.DecimalField(decimal_places=2, max_digits=13)),
                ('financing', models.DecimalField(decimal_places=2, max_digits=13)),
                ('month', models.DateField()),
                ('yearly_prod_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.yearlyproductionplan')),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('yearly_prod_plan', 'month')},
            },
        ),
        migrations.CreateModel(
            name='BaseModelProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('quantity', models.IntegerField()),
                ('money_amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('LSH', models.DecimalField(decimal_places=2, max_digits=13)),
                ('road_address', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), max_length=2, size=None)),
                ('production_type', models.CharField(choices=[('IRRIGATION', 'Irrigation'), ('PLANTING', 'Planting'), ('SAVING', 'Saving'), ('LANDSCAPE', 'Landscape')], max_length=20)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('monthly_prod_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.monthlyproductionplan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='IrrigationProduction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.basemodelproduction',),
        ),
        migrations.CreateModel(
            name='LandscapeJobProduction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.basemodelproduction',),
        ),
        migrations.CreateModel(
            name='PlantingProduction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.basemodelproduction',),
        ),
        migrations.CreateModel(
            name='SavingJobProduction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.basemodelproduction',),
        ),
    ]
