# Generated by Django 3.1.2 on 2020-12-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodelproduction',
            name='monthly_prod_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prod', to='production.monthlyproductionplan'),
        ),
        migrations.AlterField(
            model_name='monthlyproductionplan',
            name='yearly_prod_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_prod', to='production.yearlyproductionplan'),
        ),
    ]
