# Generated by Django 3.1.2 on 2020-12-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regionroad", "0015_auto_20201124_1552"),
        ("production", "0002_auto_20201205_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yearlyproductionplan",
            name="road",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yearly",
                to="regionroad.road",
            ),
        ),
    ]
