# Generated by Django 3.1.2 on 2020-12-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_auto_20201215_1204"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yearlyproductionplan",
            options={},
        ),
    ]
