# Generated by Django 3.1.2 on 2020-11-03 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DebitCredit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ("company", models.CharField(max_length=100)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "debit_expired",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "credit_expired",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("details", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
