# Generated by Django 3.1.2 on 2020-11-03 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0003_auto_20201013_0859"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debitcredit",
            name="added_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="debitcredit",
            name="organization",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.organization",
            ),
            preserve_default=False,
        ),
    ]
