# Generated by Django 3.1.2 on 2020-11-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="transfer_time",
            field=models.DateField(blank=True, null=True),
        ),
    ]
