# Generated by Django 3.1.2 on 2020-10-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regionroad', '0003_delete_organization'),
        ('account', '0002_auto_20201013_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regionroad.region'),
        ),
    ]
