# Generated by Django 3.1.2 on 2020-10-13 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import vehicles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regionroad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('manufactured_date', models.DateField()),
                ('registration_plate', models.CharField(max_length=10, validators=[vehicles.models.validate_registration_plate])),
                ('GPS_status', models.BooleanField(default=False)),
                ('storage_site', models.CharField(choices=[('OUT', 'Ташқарида'), ('IN', 'Ичкарида')], max_length=15)),
                ('balance_value', models.FloatField()),
                ('aging_value', models.FloatField()),
                ('mileage_value_start_year', models.FloatField()),
                ('mileage_value_report_time', models.FloatField()),
                ('inspection', models.DateField()),
                ('oil_change', models.DateField()),
                ('tech_state', models.CharField(choices=[('GOOD', 'Яҳши'), ('BAD', 'Носоз')], default='GOOD', max_length=5)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regionroad.organization')),
            ],
        ),
    ]
