# Generated by Django 3.1.2 on 2020-10-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20201014_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='storage_site',
            field=models.CharField(choices=[('Ташқарида', 'Ташқарида'), ('Ичкарида', 'Ичкарида')], max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tech_state',
            field=models.CharField(choices=[('Яҳши', 'Яҳши'), ('Ёмон', 'Носоз')], default='Яҳши', max_length=5),
        ),
    ]
