# Generated by Django 3.1.2 on 2020-10-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20201014_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='GPS_status',
            field=models.CharField(choices=[('Орнатилган', 'Орнатилган'), ('Орнатилмаган', 'Орнатилмаган')], max_length=12),
        ),
    ]
