# Generated by Django 3.1.2 on 2020-10-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20201014_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tech_state',
            field=models.CharField(blank=True, choices=[('Яҳши', 'Яҳши'), ('Ёмон', 'Носоз')], default='Яҳши', max_length=5, null=True),
        ),
    ]
