# Generated by Django 3.1.2 on 2020-11-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20201021_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='GPS_status',
            field=models.CharField(choices=[('Орнатилган', 'Орнатилган'), ('Орнатилмаган', 'Орнатилмаган')], default='Орнатилмаган', max_length=12),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='storage_site',
            field=models.CharField(choices=[('Ташқарида', 'Ташқарида'), ('Ичкарида', 'Ичкарида')], default='Ташқарида', max_length=15),
        ),
    ]
