# Generated by Django 3.1.2 on 2020-12-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_auto_20201124_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tech_state',
            field=models.CharField(blank=True, choices=[('Соз', 'Соз'), ('Носоз', 'Носоз')], default='Соз', max_length=5, null=True),
        ),
    ]
