# Generated by Django 3.1.2 on 2020-12-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_auto_20201212_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='storage_site',
            field=models.CharField(choices=[('Ташқарида', 'Ташқарида'), ('Айвонда', 'Айвонда')], default='Ташқарида', max_length=15),
        ),
    ]
