# Generated by Django 3.1.2 on 2020-12-18 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vehicles", "0012_auto_20201218_1732"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletypes",
            name="added_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="account.user",
            ),
            preserve_default=False,
        ),
    ]
