# Generated by Django 3.1.2 on 2021-03-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_auto_20201223_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_plate',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
