# Generated by Django 3.1.2 on 2021-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_auto_20210317_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_plate',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
