# Generated by Django 3.1.2 on 2021-03-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_auto_20210324_1029'),
        ('vehicles', '0016_auto_20210319_1200'),
    ]

    operations = [
    ]
