# Generated by Django 3.1.2 on 2021-03-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_auto_20210325_1132'),
        ('vehicles', '0018_auto_20210324_1045'),
    ]

    operations = [
    ]
